### ISSUE TITLE
glooctl  install failing on rancher k8s

### ISSUE THREAD

**Issue by debianmaster** [solo-io/sqoop#36]
```
glooctl --version
glooctl community edition version 0.13.19
```
```
k get po -n gloo-system
NAME                            READY   STATUS             RESTARTS   AGE
discovery-6db9b4ccb4-7cldc      0/1     CrashLoopBackOff   4          3m46s
gateway-7f57dd5c68-s4m7q        1/1     Running            0          3m46s
gateway-proxy-864956578-hvxq7   1/1     Running            0          3m46s
gloo-5d9d94d96b-rztvl           1/1     Running            0          3m46s
sqoop-7bf9cdcb56-n2np7          2/2     Running            0          5m31s
```

```sh
chakwifi:ant-design-pro cjonagam$ k logs -f discovery-6db9b4ccb4-7cldc -n gloo-system
{"level":"info","ts":1559050974.3741066,"logger":"fds.v1.event_loop","caller":"v1/setup_event_loop.sk.go:54","msg":"event loop started"}
{"level":"info","ts":1559050974.3755252,"logger":"uds.v1.event_loop","caller":"v1/setup_event_loop.sk.go:54","msg":"event loop started"}
{"level":"info","ts":1559050976.4867938,"logger":"uds.v1.event_loop.uds.v1.event_loop","caller":"v1/discovery_event_loop.sk.go:54","msg":"event loop started"}
{"level":"info","ts":1559050976.5874927,"logger":"uds.v1.event_loop.uds.v1.event_loop.syncer","caller":"syncer/discovery_syncer.go:32","msg":"begin sync 249222088124293320 (0 upstreams)"}
{"level":"info","ts":1559050976.6063056,"logger":"fds.v1.event_loop.fds.v1.event_loop","caller":"v1/discovery_event_loop.sk.go:54","msg":"event loop started"}
{"level":"info","ts":1559050976.9123707,"logger":"uds.v1.event_loop.uds.v1.event_loop.syncer.kube-uds","caller":"kubernetes/uds.go:28","msg":"started","watchns":[],"writens":"gloo-system"}
{"level":"info","ts":1559050976.9124694,"logger":"uds.v1.event_loop.uds.v1.event_loop.syncer","caller":"syncer/discovery_syncer.go:58","msg":"end sync 249222088124293320"}
{"level":"info","ts":1559050976.9127948,"logger":"uds.v1.event_loop.uds.v1.event_loop.syncer.kube-uds","caller":"runtime/asm_amd64.s:522","msg":"ended"}
panic: runtime error: slice bounds out of range

goroutine 355 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.UpstreamName(0xc002679550, 0xa, 0xc002679540, 0xd, 0xc000000050, 0xc0021d15a0, 0x0, 0x0)
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds_convert.go:141 +0x8e4
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.createUpstream(0x2891bc0, 0xc0013516b0, 0xc0026bb480, 0xc002679610, 0x7, 0xc002679617, 0x3, 0x50, 0x0, 0x50, ...)
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds_convert.go:113 +0x374
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*KubeUpstreamConverter).CreateUpstreamForLabels(0xc001a276d0, 0x2891bc0, 0xc0013516b0, 0xc0009121d0, 0x2, 0x2, 0xc0026bb480, 0x0, 0x0, 0x0)
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds_convert.go:51 +0x215
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*KubeUpstreamConverter).UpstreamsForService(0xc001a276d0, 0x2891bc0, 0xc0013516b0, 0xc0026bb480, 0xc00071b400, 0x4a, 0x80, 0x0, 0x0, 0x0)
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds_convert.go:44 +0xed
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).ConvertServices(0xc000d51e90, 0x2891bc0, 0xc0013516b0, 0x0, 0x0, 0x0, 0xc00071a800, 0x44, 0x80, 0xc00071b400, ...)
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:86 +0x1dd
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).DiscoverUpstreams.func1()
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:46 +0x51f
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).DiscoverUpstreams.func2(0xc001a26028, 0xc000d51e90, 0xc0003a97a0, 0xc0003a9c80, 0xc0003a9ce0, 0xc0017320a0, 0x2891bc0, 0xc0013516b0)
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:57 +0x174
created by github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).DiscoverUpstreams
	/workspace/gopath/src/github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:51 +0x62c
```

**Comment by scranton** [comment]
Hey Chak :-)

Probably better to open this issue against solo-io/gloo as its gloo related. Any more color on this? Did you ever get gloo to work on Rancher?

I don't see you on slack.solo.io. Maybe easier to chat there...

Scott

**Comment by yuval-k** [comment]
Hi!
can you please provide the version of the discovery deployment?
You can find it out using this command: `kubectl get -n gloo-system deploy/discovery -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'`

**Comment by debianmaster** [comment]
@scranton  hey scott!!   trying first time on rancher.      joined on slack

@yuval-k 
```sh
kubectl get -n gloo-system deploy/discovery -o=jsonpath='{.spec.template.spec.containers[*].image}{"\n"}'
quay.io/solo-io/discovery:0.10.2
```

**Comment by yuval-k** [comment]
good news - this is a fairly old version of gloo; this bug was fixed in  v0.11.3
closing as solved, please feel free to re-open if needed

**Comment by debianmaster** [comment]
I had picked latest version of scoop. May be doc should show which version of glooctl needs be used ?

**Comment by christian-posta** [comment]
So the latest `sqoopctl` defaults to installing a really old version of Gloo. I think that's what needs to be updated here for this issue.

**Comment by christian-posta** [comment]
@debianmaster can you try with latest release of Sqoop?
